blueprint:
  name: Master On/Off
  description: |
    ## Turn multiple switches on or off based on other switch
  domain: automation
  homeassistant:
    min_version: 2022.5.0
  input:
    source:
      name: Controller switch
      selector:
        entity:
          domain: switch
    target:
      name: Controlled switches
      selector:
        entity:
          domain: switch
          multiple: true

mode: single

variables:
  source: !input 'source'
  target: !input 'target'

trigger:
  - platform: state
    entity_id: !input 'source'
    to: "on"
  - platform: state
    entity_id: !input 'source'
    to: "off"

action:
  - service: switch.turn_{{ trigger.to_state.state }}
    metadata: {}
    data: {}
    target:
      entity_id: '{{ target }}'