blueprint:
  name: Link Multiple Switches
  description: |
    ## Link multiple switches together v1.0.1

    Select multiple switch entities to link their on/off state. If any selected switch entity is turned on or off, the other selected entities will be sent a matching on or off command.
  domain: automation
  homeassistant:
    min_version: 2022.5.0
  input:
    switches:
      name: Switch Entites
      selector:
        entity:
          domain: switch
          multiple: true

mode: single
max_exceeded: silent

variables:
  switches: !input 'switches'

trigger:
  - platform: state
    entity_id: !input 'switches'
    to: "on"
  - platform: state
    entity_id: !input 'switches'
    to: "off"

action:
  - service: switch.turn_{{ trigger.to_state.state }}
    metadata: {}
    data: {}
    target:
      entity_id: >-
        {{ expand(switches) | select('is_state', 'on' if trigger.to_state.state == 'off' else 'off') | list }}